version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"
      RAM_SIZE: "32G"
      CPU_CORES: "12"
      DISK_SIZE: "24G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /:/storage
    restart: on-failure
